# Site settings
title: "Hello World!" 
email: vergosspyros@gmail.com
url: https://example.github.io
description: "''I am Spyridon G. Vergos (aka Spiros) and this is my website. I am working on artificial inteligence models for financial applications. Press the arrow bellow to read about me.''  "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Spyridon Vergos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spirosvergos?lang=en
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: https://bitbucket.org/SpyridonVergos/
  - title: github
    url: https://github.com/SpyridonVergos

# Build settings
markdown: kramdown
permalink: pretty
